import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next App-For-Child",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul>
            <li>Home </li>
            <li>Service</li>
            <li>About</li>
          </ul>
        </nav>
        <main className="h-screen">
          {children}
        </main>
        <footer className="text-green-500 bg-red-500 text-center">This is the footer of this project</footer>
      </body>
    </html>
  );
}
