import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next-Js-For-Beginners",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <NavBar></NavBar>
        <main className="h-screen h-max-[400px] place-content-center place-items-center">
          {children}
        </main>
        <footer className="text-green-500 bg-red-500 text-center">This is the footer of this project</footer>
      </body>
    </html>
  );
}
